# Generated by Django 4.2.9 on 2024-01-14 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=77)),
                ('start_date', models.DateField()),
                ('duration', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('free_slots', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'holidays',
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=77)),
                ('number', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=77)),
                ('country', models.CharField(max_length=77)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('duration', models.PositiveIntegerField()),
                ('searchBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_agency.holidays')),
            ],
            options={
                'db_table': 'reservations',
            },
        ),
        migrations.AddField(
            model_name='holidays',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_agency.locations'),
        ),
    ]
